---
dist: bionic
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/osism-ansible
  matrix:
    - VERSION=latest

before_script:
  - bash scripts/lint.sh

script:
  - bash scripts/build.sh

deploy:
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      branch: master
